version: '3.9'

services:
    web:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        image: php-rev
    database:
        image: mysql:5.7
        ports:
            - "33061:3306"
        command: --init-file /data/application/starter.sql
        volumes:
            - ./starter.sql:/data/application/starter.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: registrations
            MYSQL_USER: user
            MYSQL_PASSWORD: password
